/* 
 * 
 * Confidential Information of Telekinesys Research Limited (t/a Havok).  Not for disclosure or distribution without Havok's
 * prior written consent.This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Level 2 and Level 3 source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2008 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 * 
 */

// Autogenerated by genRegister.py

HK_ABSTRACT_CLASS(hkaAnimatedReferenceFrame)
HK_ABSTRACT_CLASS(hkaSkeletalAnimation)
HK_CLASS(hkaDefaultAnimatedReferenceFrame)
HK_CLASS(hkaDeltaCompressedSkeletalAnimation)
HK_CLASS(hkaInterleavedSkeletalAnimation)
HK_CLASS(hkaSkeletonMapper)
HK_CLASS(hkaSplineSkeletalAnimation)
HK_CLASS(hkaWaveletSkeletalAnimation)
HK_STRUCT(hkaAnimationBinding)
HK_STRUCT(hkaAnimationContainer)
HK_STRUCT(hkaAnnotationTrack)
HK_STRUCT(hkaAnnotationTrackAnnotation)
HK_STRUCT(hkaBone)
HK_STRUCT(hkaBoneAttachment)
HK_STRUCT(hkaDeltaCompressedSkeletalAnimationQuantizationFormat)
HK_STRUCT(hkaMeshBinding)
HK_STRUCT(hkaMeshBindingMapping)
HK_STRUCT(hkaSkeleton)
HK_STRUCT(hkaSkeletonMapperData)
HK_STRUCT(hkaSkeletonMapperDataChainMapping)
HK_STRUCT(hkaSkeletonMapperDataSimpleMapping)
HK_STRUCT(hkaSplineSkeletalAnimationAnimationCompressionParams)
HK_STRUCT(hkaSplineSkeletalAnimationTrackCompressionParams)
HK_STRUCT(hkaWaveletSkeletalAnimationCompressionParams)
HK_STRUCT(hkaWaveletSkeletalAnimationQuantizationFormat)

/*
* Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20080529)
*
* Confidential Information of Havok.  (C) Copyright 1999-2008 
* Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
* Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
* rights, and intellectual property rights in the Havok software remain in
* Havok and/or its suppliers.
*
* Use of this software for evaluation purposes is subject to and indicates 
* acceptance of the End User licence Agreement for this product. A copy of 
* the license is included with this software and is also available at
* www.havok.com/tryhavok
*
*/
